default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost:3000

development:
  <<: *default
  database: mindful_development

test:
  <<: *default
  database: mindful_test

production:
  <<: *default
  database: mindful_production